import ClusterService from '../services/ClusterService.js';

class ClusterController {
  constructor() {
    this.clusterService = new ClusterService();
    
    // Bind methods to preserve 'this' context when used as Express route handlers
    this.recluster = this.recluster.bind(this);
    this.rename = this.rename.bind(this);
    this.autoName = this.autoName.bind(this);
  }

  // POST /api/cluster/recluster
  async recluster(req, res) {
    try {
      const { autoName = false } = req.body;
      const jobs = await this.clusterService.fetchUserJobs(req.userId);

      if (jobs.length < 2) {
        return res.status(400).json({ error: 'Need at least 2 jobs to cluster' });
      }

      const titles = jobs.map((j) => j.title).filter(Boolean);
      const { assignments, clusters, optimal_k } = await this.clusterService.callClusteringService(titles);

      const clusterLabels = await this.clusterService.getClusterLabels(clusters, autoName);

      await this.clusterService.bulkUpdateJobClusters(jobs, assignments, clusterLabels);

      const updatedJobs = await this.clusterService.fetchSortedJobs(req.userId);

      res.status(200).json({
        message: `Clustered ${jobs.length} jobs into ${optimal_k} groups`,
        optimal_k,
        clusterLabels,
        jobs: updatedJobs,
      });
    } catch (error) {
      console.error('Recluster error:', error.message);
      const status = error.message.includes('Clustering service') ? 502 : 500;
      res.status(status).json({
        error: error.message || 'Internal server error during reclustering',
      });
    }
  }

  // POST /api/cluster/rename
  async rename(req, res) {
    try {
      const { clusterId, newLabel } = req.body;

      if (clusterId === undefined || !newLabel) {
        return res.status(400).json({ error: 'clusterId and newLabel are required' });
      }

      const result = await this.clusterService.renameCluster(req.userId, clusterId, newLabel);

      res.status(200).json({
        message: `Renamed cluster ${clusterId} to "${newLabel}"`,
        modifiedCount: result.modifiedCount,
      });
    } catch (error) {
      console.error('Rename cluster error:', error.message);
      res.status(500).json({ error: 'Failed to rename cluster' });
    }
  }

  // POST /api/cluster/auto-name
  async autoName(req, res) {
    try {
      const jobs = await this.clusterService.fetchUserJobs(req.userId);
      const clusters = this.clusterService.groupJobsByCluster(jobs);

      if (Object.keys(clusters).length === 0) {
        return res.status(400).json({ error: 'No clustered jobs found. Run recluster first.' });
      }

      const clusterLabels = await this.clusterService.getClusterLabels(clusters, true);

      await this.clusterService.applyAutoNameLabels(req.userId, clusterLabels);

      const updatedJobs = await this.clusterService.fetchSortedJobs(req.userId);

      res.status(200).json({
        message: 'Cluster labels generated by AI',
        clusterLabels,
        jobs: updatedJobs,
      });
    } catch (error) {
      console.error('Auto-name error:', error.message);
      res.status(500).json({ error: 'Failed to auto-name clusters' });
    }
  }
}

export default ClusterController;
